Basic Layout
DKBoston15/react-notes-app pull request #1
Opened 2021-04-07 23:35 UTC by DKBoston15

Added all components
Added and partially styled a navigation menu
Added a note modal controlled by a button with bare minimum state
Added and partially styled a non-functional search bar
Added simple state to allow for multiple sets of notes on different tabs as well as an all tab

2021-04-08 09:30 UTC, bigsondev requested changes

2021-04-08 09:30 UTC, bigsondev commented on src/App.tsx
> +        <div className="App">
Remove classnames and redundant wrappers, use makeStyles for styling if needed or e.g. Container component from MUI

2021-04-08 09:30 UTC, bigsondev commented on src/App.tsx
> +import SearchBar from "./components/SearchBar";
Try to switch into named imports everywhere you can: https://mindsers.blog/en/javascript-named-imports-vs-default-imports/

2021-04-08 09:30 UTC, bigsondev commented on src/components/Note.tsx
> +import { styled } from "@material-ui/core/styles";
I think makeStyles hooks are a bit cleaner when using MUI, I'd suggest that instead of styled.

2021-04-08 09:30 UTC, bigsondev commented on src/components/Note.tsx
> +type NoteProp = {
interface, INoteProps -> should be the convention

2021-04-08 09:30 UTC, bigsondev commented on src/components/Note.tsx
> +    return <NoteCard>{name}</NoteCard>;
You can do shorten return statemenet

2021-04-08 09:30 UTC, bigsondev commented on src/components/NoteModal.tsx
> +    display: "flex",
For things like that use Box component + avoid .css if you use CSS-in-JS

2021-04-08 09:30 UTC, bigsondev commented on src/components/NotesNavigation.tsx
> +    const [homeNotes, setHomeNotes] = useState(homeNotesList);
Filtering should be done based of a tab, so just keep tab and notes in state and do filtering based on that, render what only meets a condition using e.g. filter method, so notes should have something like category as part of the object.

2021-04-08 09:30 UTC, bigsondev commented on src/components/SearchBar.tsx
> +            options={[""]}
I guess you could pass notes here for autocomplete.

2021-04-13 23:56 UTC, DKBoston15 commented on src/App.tsx
> +import SearchBar from "./components/SearchBar";
Updated to named imports

2021-04-13 23:58 UTC, DKBoston15 commented on src/components/Note.tsx
> +type NoteProp = {
Switched to interfaces

2021-04-14 00:21 UTC, DKBoston15 commented on src/components/NoteModal.tsx
> +    display: "flex",
Removed the need for .css

2021-04-14 00:27 UTC, DKBoston15 commented on src/App.tsx
> +        <div className="App">
Fixed

2021-04-14 00:29 UTC, DKBoston15 commented on src/components/Note.tsx
> +    return <NoteCard>{name}</NoteCard>;
Unsure what a shortened return statement looks like here.

2021-04-14 00:29 UTC, DKBoston15 commented on src/components/SearchBar.tsx
> +            options={[""]}
That was the plan, perhaps to pass the note name in and use that as a way to search. Do you have a better suggestion?

2021-04-14 05:48 UTC, DKBoston15 commented on src/components/NotesNavigation.tsx
> +    const [homeNotes, setHomeNotes] = useState(homeNotesList);
I made some progress with this, but am having some issues. When changing tabs, the tab state is updating only on the second click.

Additionally material UI is not happy with me only using 1 tab.

2021-04-14 05:48 UTC, DKBoston15 commented on src/components/NoteModal.tsx
> +    display: "flex",
This is a styled modal, so I am unsure how to use the box component

2021-04-14 05:48 UTC, DKBoston15 commented on src/components/Note.tsx
> +import { styled } from "@material-ui/core/styles";
I have not had a chance to migrate over to makeStyles, but I did some research on it and will make that change.

2021-04-15 04:25 UTC, DKBoston15 commented on src/components/Note.tsx
> +import { styled } from "@material-ui/core/styles";
Refactored

2021-04-15 04:26 UTC, DKBoston15 commented on src/components/NoteModal.tsx
> +    display: "flex",
Refactored

2021-04-15 04:53 UTC, DKBoston15 commented on src/components/NotesNavigation.tsx
> +    const [homeNotes, setHomeNotes] = useState(homeNotesList);
Refactored with useMemo

2021-04-15 05:38 UTC, merged